# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Author.create(name: "Aesop", wiki_desc: "Aesop (/ˈiːsɒp/ ee-sop; Ancient Greek: Αἴσωπος, Aisōpos, c. 620–564 BCE) was an Ancient Greek fabulist or story teller credited with a number of fables now collectively known as Aesop's Fables. Although his existence remains uncertain and (if he ever existed) no writings by him survive, numerous tales credited to him were gathered across the centuries and in many languages in a storytelling tradition that continues to this day. Many of the tales are characterized by animals and inanimate objects that speak, solve problems, and generally have human characteristics.
Scattered details of Aesop's life can be found in ancient sources, including Aristotle, Herodotus, and Plutarch. An ancient literary work called The Aesop Romance tells an episodic, probably highly fictional version of his life, including the traditional description of him as a strikingly ugly slave (δοῦλος) who by his cleverness acquires freedom and becomes an adviser to kings and city-states. Older spellings of his name have included Esop(e) and Isope. Depictions of Aesop in popular culture over the last 2500 years have included several works of art and his appearance as a character in numerous books, films, plays, and television programs.", wiki_url: "https://en.wikipedia.org/wiki/Aesop")

Author.find(1).quotes.create(text: "Better be wise by the misfortunes of others than by your own.")
Author.find(1).quotes.create(text: "In critical moments even the very powerful have need of the weakest.")
Author.find(1).quotes.create(text: "It is thrifty to prepare today for the wants of tomorrow.")

Author.create(name: "Aristotle", wiki_desc: "Aristotle (/ˈærɪˌstɒtəl/;Greek: Ἀριστοτέλης [aristotélɛːs], Aristotélēs; 384–322 BCE) was a Greek philosopher and scientist born in Stagira of Chalkidiki, next to the Macedonian Kingdom in the north part of the Greek world. His father, Nicomachus, died when Aristotle was a child, whereafter Proxenus of Atarneus became his guardian. At eighteen, he joined Plato's Academy in Athens and remained there until the age of thirty-seven (c. 347 BCE). His writings cover many subjects – including physics, biology, zoology, metaphysics, logic, ethics, aesthetics, poetry, theater, music, rhetoric, linguistics, politics and government – and constitute the first comprehensive system of Western philosophy. Shortly after Plato died, Aristotle left Athens and, at the request of Philip of Macedon, tutored Alexander the Great starting from 343 BCE. According to the Encyclopædia Britannica, 'Aristotle was the first genuine scientist in history ... [and] every scientist is in his debt.'
Teaching Alexander the Great gave Aristotle many opportunities and an abundance of supplies. He established a library in the Lyceum which aided in the production of many of his hundreds of books. The fact that Aristotle was a pupil of Plato contributed to his former views of Platonism, but, following Plato's death, Aristotle immersed himself in empirical studies and shifted from Platonism to empiricism. He believed all peoples' concepts and all of their knowledge was ultimately based on perception. Aristotle's views on natural sciences represent the groundwork underlying many of his works.", wiki_url: "https://en.wikipedia.org/wiki/Aristotle")

Author.find(2).quotes.create(text: "Pleasure in the job puts perfection in the work.")
Author.find(2).quotes.create(text: "Misfortune shows those who are not really friends.")
Author.find(2).quotes.create(text: "Liars when they speak the truth are not believed.")
Author.find(2).quotes.create(text: "Poverty is the parent of revolution and crime.")

Author.create(name: "Cicero", wiki_desc: "Marcus Tullius Cicero (/ˈsɪsɨroʊ/; Classical Latin: [maːrkʊs tʊlliʊs ˈkɪkɛroː]; Ancient Greek: Κικέρων Kikerōn; 3 January 106 BC – 7 December 43 BC; sometimes anglicized as Tully /ˈtʌli/), was a Roman philosopher, politician, lawyer, orator, political theorist, consul and constitutionalist. He came from a wealthy municipal family of the Roman equestrian order, and is widely considered one of Rome's greatest orators and prose stylists.
His influence on the Latin language was so immense that the subsequent history of prose in not only Latin but European languages up to the 19th century was said to be either a reaction against or a return to his style. According to Michael Grant, 'the influence of Cicero upon the history of European literature and ideas greatly exceeds that of any other prose writer in any language'. Cicero introduced the Romans to the chief schools of Greek philosophy and created a Latin philosophical vocabulary (with neologisms such as humanitas, qualitas, quantitas, and essential) distinguishing himself as a linguist, translator, and philosopher.
Petrarch's rediscovery of Cicero's letters is often credited for initiating the 14th-century Renaissance in public affairs, humanism, and classical Roman culture. According to Polish historian Tadeusz Zieliński, 'Renaissance was above all things a revival of Cicero, and only after him and through him of the rest of Classical antiquity.' The peak of Cicero's authority and prestige came during the eighteenth-century Enlightenment, and his impact on leading Enlightenment thinkers such as John Locke, David Hume, and Montesquieu was substantial. His works rank among the most influential in European culture, and today still constitute one of the most important bodies of primary material for the writing and revision of Roman history, especially the last days of the Roman Republic.", wiki_url: "https://en.wikipedia.org/wiki/Cicero")

Author.find(3).quotes.create(text: "A happy life consists in tranquillity of mind.")
Author.find(3).quotes.create(text: "Advice is judged by results, not by intentions.")
Author.find(3).quotes.create(text: "Never go to excess, but let moderation be your guide.")

Author.create(name: "Confucius", wiki_desc: "Confucius (/kənˈfjuːʃəs/; 551–479 BC) was a Chinese teacher, editor, politician, and philosopher of the Spring and Autumn period of Chinese history.
The philosophy of Confucius emphasized personal and governmental morality, correctness of social relationships, justice and sincerity. His followers competed successfully with many other schools during the Hundred Schools of Thought era only to be suppressed in favor of the Legalists during the Qin Dynasty. Following the victory of Han over Chu after the collapse of Qin, Confucius's thoughts received official sanction and were further developed into a system known as Confucianism.
Confucius is traditionally credited with having authored or edited many of the Chinese classic texts including all of the Five Classics, but modern scholars are cautious of attributing specific assertions to Confucius himself. Aphorisms concerning his teachings were compiled in the Analects, but only many years after his death.
Confucius's principles had a basis in common Chinese tradition and belief. He championed strong family loyalty, ancestor worship, respect of elders by their children and of husbands by their wives. He also recommended family as a basis for ideal government. He espoused the well-known principle 'Do not do to others what you do not want done to yourself', an early version of the Golden Rule.", wiki_url: "https://en.wikipedia.org/wiki/Confucius")

Author.find(4).quotes.create(text: "Everything has its beauty but not everyone sees it.")
Author.find(4).quotes.create(text: "He who will not economize will have to agonize.")
Author.find(4).quotes.create(text: "Wheresoever you go, go with all your heart.")
Author.find(4).quotes.create(text: "They must often change who would be constant in happiness or wisdom.")

Author.create(name: "Euripides", wiki_desc: "Euripides (/jʊəˈrɪpɨdiːz/ or /jɔːˈrɪpɨdiːz/; Greek: Εὐριπίδης) (c. 480 – 406 BC) was one of the three great tragedians of classical Athens, the other two being Aeschylus and Sophocles. Some ancient scholars attributed ninety-five plays to him but according to the Suda it was ninety-two at most. Of these, eighteen or nineteen have survived more or less complete (there has been debate about his authorship of Rhesus, largely on stylistic grounds) and there are also fragments, some substantial, of most of the other plays. More of his plays have survived intact than those of Aeschylus and Sophocles together, partly due to mere chance and partly because his popularity grew as theirs declined—he became, in the Hellenistic Age, a cornerstone of ancient literary education, along with Homer, Demosthenes and Menander.
Euripides is identified with theatrical innovations that have profoundly influenced drama down to modern times, especially in the representation of traditional, mythical heroes as ordinary people in extraordinary circumstances. This new approach led him to pioneer developments that later writers adapted to comedy, some of which are characteristic of romance. Yet he also became 'the most tragic of poets', focusing on the inner lives and motives of his characters in a way previously unknown. He was 'the creator of...that cage which is the theatre of Shakespeare's Othello, Racine's Phèdre, of Ibsen and Strindberg,' in which '...imprisoned men and women destroy each other by the intensity of their loves and hates', and yet he was also the literary ancestor of comic dramatists as diverse as Menander and George Bernard Shaw.", wiki_url: "https://en.wikipedia.org/wiki/Euripides")

Author.find(5).quotes.create(text: "Short is the joy that guilty pleasure brings.")
Author.find(5).quotes.create(text: "Do not consider painful what is good for you.")
Author.find(5).quotes.create(text: "Waste not fresh tears over old griefs.")
Author.find(5).quotes.create(text: "Your very silence shows you agree.")
Author.find(5).quotes.create(text: "A bad beginning makes a bad ending.")
Author.find(5).quotes.create(text: "Talk sense to a fool and he calls you foolish.")

Author.create(name: "Ptahhtep", wiki_desc: "Ptahhotep (ptāħ ħwtp), sometimes known as Ptahhotpe or Ptah-Hotep, was an ancient Egyptian official during the late 25th century BC and early 24th century BC.", wiki_url: "https://en.wikipedia.org/wiki/Ptahhotep")

Author.find(6).quotes.create(text: " Be a craftsman in speech that thou mayest be strong, for the strength of one is the tongue, and speech is mightier than all fighting.")

Author.create(name: "Plato", wiki_desc: "Plato (/ˈpleɪtoʊ/; Greek: Πλάτων, Plátōn, 'broad'; 428/427 or 424/423[a] – 348/347 BCE) was a philosopher, as well as mathematician, in Classical Greece, and an influential figure in philosophy, central in Western philosophy. He was Socrates' student, and founded the Academy in Athens, the first institution of higher learning in the Western world. Along with Socrates and his most famous student, Aristotle, Plato helped to lay the foundations of Western philosophy and science. Alfred North Whitehead once noted: 'the safest general characterization of the European philosophical tradition is that it consists of a series of footnotes to Plato.'
Plato's dialogues have been used to teach a range of subjects, including philosophy, logic, ethics, rhetoric, religion and mathematics. His theory of Forms began a unique perspective on abstract objects, and led to a school of thought called Platonism. Plato's writings have been published in several fashions; this has led to several conventions regarding the naming and referencing of Plato's texts.", wiki_url: "https://en.wikipedia.org/wiki/Plato")

Author.find(7).quotes.create(text: "Not even the gods fight against necessity.")

Author.create(name: "Protagoras", wiki_desc: "Protagoras (/proʊˈtæɡərəs/; Greek: Πρωταγόρας; c. 490 – c. 420 BC)[1] was a pre-Socratic Greek philosopher and is numbered as one of the sophists by Plato. In his dialogue, Protagoras, Plato credits him with having invented the role of the professional sophist.
He also is believed to have created a major controversy during ancient times through his statement that, 'Man is the measure of all things', interpreted to mean that there is no absolute truth, but that which individuals deem to be the truth. Although there is reason to question the extent of the interpretation of his arguments that has followed, that concept of individual relativity was revolutionary for the time, and contrasted with other philosophical doctrines that claimed the universe was based on something objective, outside of human influence or perceptions.", wiki_url: "https://en.wikipedia.org/wiki/Protagoras")

Author.find(8).quotes.create(text: "Man is the measure of all things.")
Author.find(8).quotes.create(text: " There are two sides to every question.")

Author.create(name: "Zeuxis", wiki_desc: "Zeuxis (/ˈzuːksɪs/; Greek: Ζεῦξις)[1] (of Heraclea) was a painter who flourished during the 5th century BC.", wiki_url: "https://en.wikipedia.org/wiki/Zeuxis")

Author.find(9).quotes.create(text: "Criticism comes easier than craftsmanship.")

Author.create(name: "Polybius", wiki_desc: "Polybius (/pəˈlɪbiəs/; Greek: Πολύβιος, Polýbios; c. 200 – c. 118 BC) was a Greek historian of the Hellenistic Period noted for his work, The Histories, which covered the period of 264–146 BC in detail. The work describes the rise of the Roman Republic to 'world power' (i.e. domination over the Mediterranean world). Polybius is also renowned for his ideas concerning the separation of powers in government, later used in Montesquieu's The Spirit of the Laws and in the drafting of the United States Constitution.
Polybius was born in Arcadia around 200 BC. He was the son of Lycortas, a Greek politician who became Cavalry Commander of the Achaean League. His father's opposition to Roman control of Macedonia resulted in his imprisonment. Polybius was then deported to Rome, where Lucius Aemilius Paulus employed him to tutor his two sons.
Polybius had the opportunity to return to Macedonia in 152 BC; he elected to stay, however, in Rome, as by that time he had placed his allegiance in the Roman Republic. He became a close friend of the Roman military commander Scipio Aemilianus, accompanying the general to Hispania and Africa. He was also among the members of the Scipionic Circle. Polybius's The Histories provides a detailed account of Rome's ascent to empire and included his eyewitness account of the Sack of Carthage in 146 BC. Polybius held that historians should only chronicle events whose participants the historian was able to interview, and was among the first to champion the notion of having factual integrity in historical writing, while avoiding bias.", wiki_url: "https://en.wikipedia.org/wiki/Polybius")

Author.find(10).quotes.create(text: "Those who know how to win are much more numerous than those who know how to make proper use of their victories.")
Author.find(10).quotes.create(text: "There is no witness so dreadful, no accuser so terrible as the conscience that dwells in the heart of every man.")


Author.create(name: "Phaedrus", wiki_desc: "Phaedrus (/ˈfiːdrəs, ˈfɛdrəs/), son of Pythocles, of the Myrrhinus deme (Greek: Φαῖδρος Πυθοκλέους Μυρρινούσιος, Phaĩdros Puthocléous Murrinoúsios; c. 444 – 393 BCE), was an ancient Athenian aristocrat associated with the inner-circle of the philosopher Socrates. He was indicted in the profanation of the Eleusinian mysteries in 415 during the Peloponnesian War, causing him to flee Athens. He is best known for his depiction in the writing of Plato: his philosophically erotic role in his eponymous dialogue and the Symposium inspired later authors, from the ancient comedic playwright Alexis to contemporary philosophers like Martha Nussbaum.[2]", wiki_url: "https://en.wikipedia.org/wiki/Phaedrus_(Athenian)")
Author.find(11).quotes.create(text: "To add insult to injury.")
Author.find(11).quotes.create(text: "The mind ought sometimes to be diverted that it may return the better to thinking.")
Author.find(11).quotes.create(text: "The humble suffer when the mighty disagree.")
Author.find(11).quotes.create(text: "There is danger in both belief and unbelief.")
Author.find(11).quotes.create(text: "Men in however high a station ought to fear the humble.")
Author.find(11).quotes.create(text: "Aggression unchallenged is aggression unleashed.")
Author.find(11).quotes.create(text: "It is destruction to the weak man to attempt to imitate the powerful.")


Author.create(name: "Thales", wiki_desc: "Thales of Miletus (/ˈθeɪliːz/; Greek: Θαλῆς (ὁ Μιλήσιος), Thalēs; c. 624 – c. 546 BC) was a pre-Socratic Greek philosopher from Miletus in Asia Minor, and one of the Seven Sages of Greece. Many, most notably Aristotle, regard him as the first philosopher in the Greek tradition. Aristotle reported Thales' hypothesis about the nature of matter – that the originating principle of nature was a single material substance: water.
According to Bertrand Russell, 'Western philosophy begins with Thales.' Thales attempted to explain natural phenomena without reference to mythology and was tremendously influential in this respect. Almost all of the other Pre-Socratic philosophers follow him in attempting to provide an explanation of ultimate substance, change, and the existence of the world without reference to mythology. Those philosophers were also influential and eventually Thales' rejection of mythological explanations became an essential idea for the scientific revolution. He was also the first to define general principles and set forth hypotheses, and as a result has been dubbed the 'Father of Science,' though it is argued that Democritus is actually more deserving of this title.
In mathematics, Thales used geometry to solve problems such as calculating the height of pyramids and the distance of ships from the shore. He is credited with the first use of deductive reasoning applied to geometry, by deriving four corollaries to Thales' Theorem. As a result, he has been hailed as the first true mathematician and is the first known individual to whom a mathematical discovery has been attributed.", wiki_url: "https://en.wikipedia.org/wiki/Thales")
Author.find(12).quotes.create(text: "Know thyself.")
Author.find(12).quotes.create(text: "The past is certain, the future obscure.")
Author.find(12).quotes.create(text: "A multitude of words is no proof of a prudent mind.")


Author.create(name: "Thrasymachus", wiki_desc: "Thrasymachus (/θræˈsiːməkəs/; Greek: Θρασύμαχος; c. 459 – c. 400 BCE) was a sophist of Ancient Greece best known as a character in Plato's Republic.", wiki_url: "https://en.wikipedia.org/wiki/Thrasymachus")
Author.find(13).quotes.create(text: "Justice is simply the advantage of the stronger.")

Author.create(name: "Demosthenes", wiki_desc: "Demosthenes (/dɪˈmɒs.θəniːz/; Greek: Δημοσθένης Dēmosthénēs [dɛːmostʰénɛːs]; 384–322 BC) was a prominent Greek statesman and orator of ancient Athens. His orations constitute a significant expression of contemporary Athenian intellectual prowess and provide an insight into the politics and culture of ancient Greece during the 4th century BC. Demosthenes learned rhetoric by studying the speeches of previous great orators. He delivered his first judicial speeches at the age of 20, in which he argued effectively to gain from his guardians what was left of his inheritance. For a time, Demosthenes made his living as a professional speech-writer (logographer) and a lawyer, writing speeches for use in private legal suits.
Demosthenes grew interested in politics during his time as a logographer, and in 354 BC he gave his first public political speeches. He went on to devote his most productive years to opposing Macedon's expansion. He idealized his city and strove throughout his life to restore Athens's supremacy and motivate his compatriots against Philip II of Macedon. He sought to preserve his city's freedom and to establish an alliance against Macedon, in an unsuccessful attempt to impede Philip's plans to expand his influence southward by conquering all the Greek states. After Philip's death, Demosthenes played a leading part in his city's uprising against the new King of Macedonia, Alexander the Great. However, his efforts failed and the revolt was met with a harsh Macedonian reaction. To prevent a similar revolt against his own rule, Alexander's successor in this region, Antipater, sent his men to track Demosthenes down. Demosthenes took his own life, in order to avoid being arrested by Archias, Antipater's confidant.
The Alexandrian Canon compiled by Aristophanes of Byzantium and Aristarchus of Samothrace recognized Demosthenes as one of the ten greatest Attic orators and logographers. Longinus likened Demosthenes to a blazing thunderbolt, and argued that he 'perfected to the utmost the tone of lofty speech, living passions, copiousness, readiness, speed'. Quintilian extolled him as lex orandi ('the standard of oratory'), and Cicero said about him that inter omnis unus excellat ('he stands alone among all the orators'), and he also acclaimed him as 'the perfect orator' who lacked nothing.", wiki_url: "https://en.wikipedia.org/wiki/Demosthenes")
Author.find(14).quotes.create(text: "He who confers a favor should at once forget it, if he is not to show a sordid ungenerous spirit.")
Author.find(14).quotes.create(text: "To remind a man of a kindness conferred and to talk of it, is little different from reproach.")
Author.find(14).quotes.create(text: "Beware lest in your anxiety to avoid war you obtain a master.")
Author.find(14).quotes.create(text: "Small opportunities are often the beginning of great enterprises.")
Author.find(14).quotes.create(text: "Nothing is easier than self-deceit. For what each man wishes, that he also believes to be true.")
Author.find(14).quotes.create(text: "A man is his own easiest dupe, for what he wishes to be true he generally believes to be true.")
Author.find(14).quotes.create(text: "The readiest and surest way to get rid of censure, is to correct ourselves.")
Author.find(14).quotes.create(text: "To remind a man of the good turns you have done him is very much like a reproach.")
Author.find(14).quotes.create(text: "What we have in us of the image of God is the love of truth and justice.")

Author.create(name: "Pythagoras", wiki_desc: "Pythagoras of Samos (US /pɪˈθæɡərəs/; UK /paɪˈθæɡərəs/; Greek: Πυθαγόρας ὁ Σάμιος Pythagóras ho Sámios 'Pythagoras the Samian', or simply Πυθαγόρας; Πυθαγόρης in Ionian Greek; c. 570 – c. 495 BC) was an Ionian Greek philosopher, mathematician, and founder of the religious movement called Pythagoreanism. Most of the information about Pythagoras was written down centuries after he lived, so very little reliable information is known about him. He was born on the island of Samos, and might have travelled widely in his youth, visiting Egypt and other places seeking knowledge. Around 530 BC, he moved to Croton, in Magna Graecia, and there set up a religious sect. His followers pursued the religious rites and practices developed by Pythagoras and studied his philosophical theories. The society took an active role in the politics of Croton but this eventually led to their downfall. Pythagorean meeting-places were burned and Pythagoras was forced to flee the city. He is said to have died in Metapontum.
Pythagoras made influential contributions to philosophy and religion in the late 6th century BC. He is often revered as a great mathematician, mystic, and scientist and is best known for the Pythagorean theorem which bears his name. However, because legend and obfuscation cloud his work even more than that of the other pre-Socratic philosophers, one can give only a tentative account of his teachings, and some have questioned whether he contributed much to mathematics or natural philosophy. Many of the accomplishments credited to Pythagoras may actually have been accomplishments of his colleagues and successors. Whether or not his disciples believed that everything was related to mathematics and that numbers were the ultimate reality is unknown. It was said that he was the first man to call himself a philosopher, or lover of wisdom, and Pythagorean ideas exercised a marked influence on Plato, and through him, all of Western philosophy.", wiki_url: "https://en.wikipedia.org/wiki/Pythagoras")
Author.find(15).quotes.create(text: "It is better wither to be silent, or to say things of more value than silence.")
Author.find(15).quotes.create(text: "Sooner throw a pearl at hazard than an idle or useless word; and do not say a little in many words, but a great deal in a few.")

Author.create(name: "Heraclitus", wiki_desc: "Heraclitus of Ephesus (/ˌhɛrəˈklaɪtəs/;[ Greek: Ἡράκλειτος ὁ Ἐφέσιος, Hērákleitos ho Ephésios; c. 535 – c. 475 BCE) was a pre-Socratic Greek philosopher, a native of the Greek city Ephesus, Ionia, on the coast of Asia Minor. He was of distinguished parentage. Little is known about his early life and education, but he regarded himself as self-taught and a pioneer of wisdom. From the lonely life he led, and still more from the riddling and paradoxical nature of his philosophy and his stress upon the needless unconsciousness of humankind, he was called 'The Obscure' and the 'Weeping Philosopher'.
Heraclitus is famous for his insistence on ever-present change in the universe, as stated in the famous saying, 'No man ever steps in the same river twice' (see panta rhei, below). He believed in the unity of opposites, stating that 'the path up and down are one and the same', all existing entities being characterized by pairs of contrary properties. His cryptic utterance that 'all entities come to be in accordance with this Logos' (literally, 'word', 'reason', or 'account') has been the subject of numerous interpretations.", wiki_url: "https://en.wikipedia.org/wiki/Heraclitus")
Author.find(16).quotes.create(text: "A man's character is his fate.")

Author.create(name: "Apuleius", wiki_desc: "Apuleius (/ˌæpjʉˈliːəs/; also called Lucius Apuleius Madaurensis; c. 124 – c. 170 CE) was a Latin-language prose writer. He was a Numidian Berber and lived under the Roman Empire. He was from Madaurus (now M'Daourouch, Algeria). He studied Platonist philosophy in Athens; travelled to Italy, Asia Minor and Egypt; and was an initiate in several cults or mysteries. The most famous incident in his life was when he was accused of using magic to gain the attentions (and fortune) of a wealthy widow. He declaimed and then distributed a witty tour de force in his own defense before the proconsul and a court of magistrates convened in Sabratha, near ancient Tripoli, Libya. This is known as the Apologia.
His most famous work is his bawdy picaresque novel, the Metamorphoses, otherwise known as The Golden Ass. It is the only Latin novel that has survived in its entirety. It relates the ludicrous adventures of one Lucius, who experiments with magic and is accidentally turned into a donkey.", wiki_url: "https://en.wikipedia.org/wiki/Apuleius")
Author.find(17).quotes.create(text: "Familiarity breeds contempt, while rarity wins admiration.")

Author.create(name: "Marcus Valerius Martialis", wiki_desc: "Marcus Valerius Martialis (known in English as Martial /ˈmɑrʃəl/) (March 1, between 38 and 41 AD – between 102 and 104 AD), was a Roman poet from Hispania (the Iberian Peninsula) best known for his twelve books of Epigrams, published in Rome between AD 86 and 103, during the reigns of the emperors Domitian, Nerva and Trajan. In these short, witty poems he cheerfully satirises city life and the scandalous activities of his acquaintances, and romanticises his provincial upbringing. He wrote a total of 1,561, of which 1,235 are in elegiac couplets. He is considered to be the creator of the modern epigram.", wiki_url: "https://en.wikipedia.org/wiki/Martial")
Author.find(18).quotes.create(text: "Conceal a flaw, and the world will imagine the worst.")

Author.create(name: "Democritus", wiki_desc: "Democritus (/dɪˈmɒkrɪtəs/; Greek: Δημόκριτος Dēmókritos, meaning 'chosen of the people'; c. 460 – c. 370 BC) was an influential Ancient Greek pre-Socratic philosopher primarily remembered today for his formulation of an atomic theory of the universe.
Democritus was born in Abdera, Thrace around 460 BC. His exact contributions are difficult to disentangle from those of his mentor Leucippus, as they are often mentioned together in texts. Their speculation on atoms, taken from Leucippus, bears a passing and partial resemblance to the nineteenth-century understanding of atomic structure that has led some to regard Democritus as more of a scientist than other Greek philosophers; however, their ideas rested on very different bases. Largely ignored in ancient Athens, Democritus was nevertheless well known to his fellow northern-born philosopher Aristotle. Plato is said to have disliked him so much that he wished all his books burned. Many consider Democritus to be the 'father of modern science'.", wiki_url: "https://en.wikipedia.org/wiki/Democritus")
Author.find(19).quotes.create(text: "By desiring little, a poor man makes himself rich.")
Author.find(19).quotes.create(text: "Do not trust all men, but trust men of worth; the former course is silly, the latter a mark of prudence.")
Author.find(19).quotes.create(text: "Happiness resides not in possessions, and not in gold, happiness dwells in the soul.")
Author.find(19).quotes.create(text: "Hope of ill gain is the beginning of loss.")
Author.find(19).quotes.create(text: "If thou suffer injustice, console thyself; the true unhappiness is in doing it.")
Author.find(19).quotes.create(text: "Now as of old the gods give men all good things, excepting only those that are baneful and injurious and useless. These, now as of old, are not gifts of the gods: men stumble into them themselves because of their own blindness and folly.")
Author.find(19).quotes.create(text: "The wrongdoer is more unfortunate than the man wronged.")